### ISSUE TITLE
Encryption bug

### ISSUE THREAD

**Issue by danzaph** [shameerariff/crypt#1]
There is a bug in the C and ObjC versions that writes an extra byte to the output fie on encryption.

**Comment by shameerariff** [comment]
Hi, Thank you for your update. I will check with the same. If you provide me more details it will be appreciated.

**Comment by shameerariff** [comment]
This bug was cleared. 
We appreciate your interest on our application. If you find any bugs in the future kindly update us.
Thank you for your cooperation.
